version: "3.8"

services:
  nginx:
    build: ./nginx
    volumes:
      - static:/home/www/static
      - media:/home/www/media
    ports:
      - 80:80
  django_app:
    build:
      context: ./
      dockerfile: ./django/Dockerfile
    ports:
      - 8001:8001
    command: bash /play_with_image/run_server.sh
    env_file:
      - "play_with_image/.env"
    volumes:
      - ./play_with_image:/play_with_image
      - static:/static
      - media:/media
    depends_on:
      - db
  db:
    image: postgres:13.10
    env_file:
      - "play_with_image/.env"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  static:
  media:


