version: "3.8"

services:
  nginx:
    build: ./nginx
    volumes:
      - django_static:/home/www/static
      - django_media:/home/www/media
    ports:
      - 80:80
  django_app:
    build:
      context: ./
      dockerfile: ./django/Dockerfile
    command: bash /play_with_image/run_server.sh
    env_file:
      - "play_with_image/.env"
    volumes:
      - django_static:/static
      - django_media:/media
      - django_logs:/play_with_image/logs
    depends_on:
      - db
  db:
    image: postgres:13.10
    env_file:
      - "play_with_image/.env"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  django_static:
  django_media:
  django_logs:


