version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: "nginx_cont"
    volumes:
      - ./play_with_image/static:/home/www/static
      - ./play_with_image/media:/home/www/media
    ports:
      - 80:80
    depends_on:
      - django_app
  django_app:
    image: python
    build:
      context: ./
      dockerfile: ./django/Dockerfile
    container_name: "django_cont"
    ports:
      - 8001:8001
    command: gunicorn play_with_image.wsgi --bind 0.0.0.0:8001
    env_file:
      - "play_with_image/.env"
    volumes:
      - ./play_with_image:/play_with_image


