# Generated by Django 4.2.1 on 2023-06-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_anything', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ('name',), 'verbose_name': 'категория тегов', 'verbose_name_plural': 'Категории тегов'},
        ),
    ]
