# Generated by Django 4.2.1 on 2023-06-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_anything', '0002_alter_tagcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tag_anything.tagcategory', verbose_name='Категория'),
        ),
    ]
