# Generated by Django 4.2.1 on 2023-06-09 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag_anything', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Загружено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image_hash', models.CharField(editable=False, max_length=16, verbose_name='Хеш изображения')),
                ('image_hash_part1', models.IntegerField(editable=False, verbose_name='Хеш 1/4')),
                ('image_hash_part2', models.IntegerField(editable=False, verbose_name='Хеш 2/4')),
                ('image_hash_part3', models.IntegerField(editable=False, verbose_name='Хеш 3/4')),
                ('image_hash_part4', models.IntegerField(editable=False, verbose_name='Хеш 4/4')),
                ('private', models.BooleanField(default=False, verbose_name='Не публиковать')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(to='tag_anything.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('-created',),
                'default_related_name': 'images',
            },
        ),
    ]
