# Generated by Django 4.2.1 on 2023-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_hash',
            field=models.CharField(blank=True, editable=False, max_length=16, verbose_name='Хеш изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part1',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Хеш 1/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part2',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Хеш 2/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part3',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Хеш 3/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part4',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Хеш 4/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='private',
            field=models.BooleanField(blank=True, default=False, verbose_name='Не публиковать'),
        ),
    ]
