# Generated by Django 4.2.1 on 2023-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_image_hash_alter_image_image_hash_part1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_hash',
            field=models.CharField(editable=False, max_length=16, null=True, verbose_name='Хеш изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part1',
            field=models.IntegerField(editable=False, null=True, verbose_name='Хеш 1/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part2',
            field=models.IntegerField(editable=False, null=True, verbose_name='Хеш 2/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part3',
            field=models.IntegerField(editable=False, null=True, verbose_name='Хеш 3/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_hash_part4',
            field=models.IntegerField(editable=False, null=True, verbose_name='Хеш 4/4'),
        ),
        migrations.AlterField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False, null=True, verbose_name='Не публиковать'),
        ),
    ]
