# Generated by Django 4.2.1 on 2023-06-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_image_image_hash_alter_image_image_hash_part1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera_model',
            field=models.CharField(max_length=255, null=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='image',
            name='exposure_time',
            field=models.CharField(max_length=10, null=True, verbose_name='Время Экспозиции'),
        ),
        migrations.AddField(
            model_name='image',
            name='f',
            field=models.FloatField(null=True, verbose_name='Диафрагма'),
        ),
        migrations.AddField(
            model_name='image',
            name='flash',
            field=models.BooleanField(null=True, verbose_name='Вспышка'),
        ),
        migrations.AddField(
            model_name='image',
            name='focal_length',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Фокусное Расстояние'),
        ),
        migrations.AddField(
            model_name='image',
            name='iso',
            field=models.PositiveIntegerField(null=True, verbose_name='ISO'),
        ),
        migrations.AddField(
            model_name='image',
            name='lens_model',
            field=models.CharField(max_length=255, null=True, verbose_name='Объектив'),
        ),
        migrations.AlterField(
            model_name='image',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Приватное'),
        ),
    ]
