# Generated by Django 4.2.1 on 2023-06-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_camera_model_image_exposure_time_image_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='focal_length',
            field=models.FloatField(null=True, verbose_name='Фокусное Расстояние'),
        ),
    ]
