# Generated by Django 4.2.1 on 2023-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_alter_image_focal_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='latitude',
            field=models.CharField(max_length=11, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='image',
            name='longitude',
            field=models.CharField(max_length=11, null=True, verbose_name='Долгота'),
        ),
    ]
